apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-poc-projects
  namespace: argocd
spec:
  generators:
  - git:
      # git repository to get the variables from
      repoURL: https://github.com/iamraj007/Argo-AppSet
      # branch used to get the variables from 
      revision: main
      directories:
      # path to the directory that includes directories to read as variables
      - path: deploymnet/*
  template:
    metadata:
      # basename is the name of the directory not the full path
      name: '{{path.basename}}'
    spec:
      project: assessment
      source:
        # source repo, in this example both repositories are the same
        repoURL:  https://github.com/iamraj007/Argo-AppSet
        targetRevision: main
        # path to read manifests from, here it's the full path not only the name of the directory
        path: '{{path}}'
        directory:
          jsonnet:
            extVars:
              - name: MyVar
                value: ClusterVar01
                code: true
      destination:
        server: https://kubernetes.default.svc
        # different namespaces named after the directories names to be used as destinations
        namespace: dev
        #namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true      
