apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitops-nginx
  name: gitops-nginx-svc
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    app: gitops-nginx
